name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: .
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: docker

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: docker

      - name: Load Docker image
        run: docker load -i docker/my-docker-image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-docker-image ${{ secrets.DOCKER_HUB_USERNAME}}/my-docker-image
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-image

# Secrets configuration
# Secrets should be added in the repository settings
# DOCKERHUB_USERNAME: <your Docker Hub username>
# DOCKERHUB_PASSWORD: <your Docker Hub password>
